package ir.atitec.signalgoApp;

import java.util.Date;

// AUTO GENERATED
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// AUTO GENERATED
public class UserInfo{

        public UserInfo() {
            
        }
         private int id;
         private String userName;
         private String password;
         private String cooperationPassword;
         private String guid;
         private int publicId;
         private Date createdDateTime;
         private int creatorUserId;
         private boolean isDeleted;
         private UserInfo creatorUserInfo;
         public int getId(){
                 return id;
         }
         public void setId(int id){
                 this.id = id;
         }
         public String getUserName(){
                 return userName;
         }
         public void setUserName(String userName){
                 this.userName = userName;
         }
         public String getPassword(){
                 return password;
         }
         public void setPassword(String password){
                 this.password = password;
         }
         public String getCooperationPassword(){
                 return cooperationPassword;
         }
         public void setCooperationPassword(String cooperationPassword){
                 this.cooperationPassword = cooperationPassword;
         }
         public String getGuid(){
                 return guid;
         }
         public void setGuid(String guid){
                 this.guid = guid;
         }
         public int getPublicId(){
                 return publicId;
         }
         public void setPublicId(int publicId){
                 this.publicId = publicId;
         }
         public Date getCreatedDateTime(){
                 return createdDateTime;
         }
         public void setCreatedDateTime(Date createdDateTime){
                 this.createdDateTime = createdDateTime;
         }
         public int getCreatorUserId(){
                 return creatorUserId;
         }
         public void setCreatorUserId(int creatorUserId){
                 this.creatorUserId = creatorUserId;
         }
         public boolean getIsDeleted(){
                 return isDeleted;
         }
         public void setIsDeleted(boolean isDeleted){
                 this.isDeleted = isDeleted;
         }
         public UserInfo getCreatorUserInfo(){
                 return creatorUserInfo;
         }
         public void setCreatorUserInfo(UserInfo creatorUserInfo){
                 this.creatorUserInfo = creatorUserInfo;
         }
    }

